image:
  file: .gitpod.Dockerfile

tasks:
  - name: API server
    # One time initialization, executed at workspace creation.
    init: |
      cd packages/api
      cp .env.default .env
      npm install
      pg_start
      psql -c 'CREATE DATABASE "pg-litefarm";'
      psql -c "CREATE DATABASE test_farm;"
      psql -tc "SELECT 1 FROM pg_user WHERE usename = 'postgres'" | grep -q 1 || psql -c "CREATE ROLE postgres"
      psql -c "ALTER ROLE postgres WITH LOGIN SUPERUSER PASSWORD 'postgres';"
      npm run migrate:dev:db
      cd ../..
    # Start up command, executed each time workspace is opened.
    command: cd packages/api && npm start
  - name: Web app server
    # One time initialization, executed at workspace creation.
    init: |
      cd packages/webapp
      cp .env.default .env
      npm install
      cd ../..
    # Start up command, executed each time workspace is opened.
    command: cd packages/webapp && npm start

vscode:
  extensions:
    - dbaeumer.vscode-eslint

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 5000
    visibility: public
    onOpen: ignore
  - port: 5432
    visibility: private
    onOpen: ignore
