image:
  file: .gitpod.Dockerfile

tasks:
  - name: API server
    init: |
      cd packages/api
      cp .env.default .env
      npm install
    command: npm start
  - name: Web app server
    init: |
      cd packages/webapp
      cp .env.default .env
      npm install
    command: npm start
    
vscode:
  extensions:
    - dbaeumer.vscode-eslint

ports:
  - port: 3000
    onOpen: open-preview
