image:
  file: .gitpod.Dockerfile

tasks:
  - name: API server
    init: cd packages/api && npm install
    command: cd packages/api 2> /dev/null; npm start
  - name: Web app server
    init: cd packages/webapp && npm install
    command: cd packages/webapp 2> /dev/null; npm start

vscode:
  extensions:
    - dbaeumer.vscode-eslint

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 5000
    visibility: public
    onOpen: ignore
  - port: 5432
    visibility: private
    onOpen: ignore
