version: "3.7"

volumes:
  postgres-data:
    driver: local

services:
  backend:
    image: litefarm/backend:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: litefarm/frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./ci/nginx.conf:/etc/nginx/nginx.conf
